#spring.sql.init.mode=always
#spring.datasource.initialization-mode=always # Spring Boot <v2.5.0
#spring.sql.init.platform=h2
#spring.datasource.platform=h2
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.defer-datasource-initialization=true
spring:
  profiles:
    active: dev