spring:
  h2:
    console:
      path: /h2
      enabled: true
  datasource:
    username: root
    password: root
    url: jdbc:h2:mem:regescweb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver